/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AssistirRouteImport } from './routes/assistir'
import { Route as IndexRouteImport } from './routes/index'

const AssistirRoute = AssistirRouteImport.update({
  id: '/assistir',
  path: '/assistir',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistir': typeof AssistirRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistir': typeof AssistirRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistir': typeof AssistirRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/assistir'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/assistir'
  id: '__root__' | '/' | '/assistir'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistirRoute: typeof AssistirRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/assistir': {
      id: '/assistir'
      path: '/assistir'
      fullPath: '/assistir'
      preLoaderRoute: typeof AssistirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistirRoute: AssistirRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
